name: Build
on:
  workflow_call:
    inputs:
      bin-name:
        required: true
        type: string
      go-version:
        required: true
        type: string
        default: '1.23.1'
      pre-build-script:
        required: false
        type: string
    secrets:
      apple_api_key_id:
        description: App Store Connect API key ID
        required: true
      apple_issuer_id:
        description: App Store Connect API key issuer ID
        required: true
      apple_private_key:
        description: App Store Connect API private key (base64)
        required: true
      apple_signing_certificate:
        description: Developer signing certificate (base64)
        required: true
      apple_signing_password:
        description: Developer signing certificate password
        required: true
env:
  BIN_NAME: ${{ inputs.bin-name }}
  GO_VERSION: ${{ inputs.go-version }}
  AC_API_KEY_ID: ${{ secrets.apple_api_key_id }}
  AC_ISSUER_ID: ${{ secrets.apple_issuer_id }}
  AC_PRIVATE_KEY: ${{ secrets.apple_private_key }}
  SIGNING_CERTIFICATE: ${{ secrets.apple_signing_certificate }}
  SIGNING_CERT_PASSWORD: ${{ secrets.apple_signing_password }}
jobs:
  build-windows:
    runs-on: ubuntu-latest
    name: Windows
    env:
      DIST_OS: windows
      DIST_ARCH: arm64 amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pre-build script
        if: ${{ inputs.pre-build-script != '' }}
        run: ${{ inputs.pre-build-script }}
      
      - name: Test how conditional step looks when false
        if: ${{ inputs.pre-build-script == '' }}
        run: echo uh oh

      - name: Build project
        run: make dist

      - name: Prepare arm64 artifact
        run: mv dist/*_arm64 ./${BIN_NAME}

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-windows-arm64
          path: ${{ env.BIN_NAME }}

      - name: Prepare amd64 artifact
        run: mv dist/*_amd64 ./${BIN_NAME}

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-windows-amd64
          path: ${{ env.BIN_NAME }}

  build-linux:
    runs-on: ubuntu-latest
    name: Linux
    env:
      DIST_OS: linux
      DIST_ARCH: arm64 amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pre-build script
        if: ${{ inputs.pre-build-script != '' }}
        run: ${{ inputs.pre-build-script }}

      - name: Build project
        run: make dist

      - name: Prepare arm64 artifact
        run: mv dist/*_arm64 ./${BIN_NAME}

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-linux-arm64
          path: ${{ env.BIN_NAME }}

      - name: Prepare amd64 artifact
        run: mv dist/*_amd64 ./${BIN_NAME}

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-linux-amd64
          path: ${{ env.BIN_NAME }}

  build-darwin-arm64:
    runs-on: macos-latest
    name: Darwin (arm64)
    env:
      DIST_OS: darwin
      DIST_ARCH: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup signing certificate and notarytool
        run: |
          echo "$SIGNING_CERTIFICATE" | base64 --decode > cert.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import cert.p12 -k build.keychain -P "$SIGNING_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          echo "$AC_PRIVATE_KEY" | base64 --decode > private_key.p8
          xcrun notarytool store-credentials --key private_key.p8 \
            --key-id "$AC_API_KEY_ID" --issuer "$AC_ISSUER_ID" ac-profile

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pre-build script
        if: ${{ inputs.pre-build-script != '' }}
        run: ${{ inputs.pre-build-script }}

      - name: Build project
        run: |
          make dist
          mv dist/*_arm64 ./${BIN_NAME}

      - name: Sign
        run: |
          codesign --timestamp --options runtime --sign "Developer ID Application" ./${BIN_NAME}

      - name: Notarize
        run: |
          zip ${BIN_NAME}.zip ${BIN_NAME}
          xcrun notarytool submit ${BIN_NAME}.zip --keychain-profile ac-profile --wait

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-darwin-arm64
          path: ${{ env.BIN_NAME }}

  build-darwin-amd64:
    runs-on: macos-13
    name: Darwin (amd64)
    env:
      DIST_OS: darwin
      DIST_ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup signing certificate and notarytool
        run: |
          echo "$SIGNING_CERTIFICATE" | base64 --decode > cert.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import cert.p12 -k build.keychain -P "$SIGNING_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          echo "$AC_PRIVATE_KEY" | base64 --decode > private_key.p8
          xcrun notarytool store-credentials --key private_key.p8 \
            --key-id "$AC_API_KEY_ID" --issuer "$AC_ISSUER_ID" ac-profile

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pre-build script
        if: ${{ inputs.pre-build-script != '' }}
        run: ${{ inputs.pre-build-script }}

      - name: Build project
        run: |
          make dist
          mv dist/*_amd64 ./${BIN_NAME}

      - name: Sign
        run: |
          codesign --timestamp --options runtime --sign "Developer ID Application" ./${BIN_NAME}

      - name: Notarize
        run: |
          zip ${BIN_NAME}.zip ${BIN_NAME}
          xcrun notarytool submit ${BIN_NAME}.zip --keychain-profile ac-profile --wait

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-darwin-amd64
          path: ${{ env.BIN_NAME }}