name: Build VSCode Web
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: vscode-web
jobs:
  detect:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.vscode }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vscode:
              - "${{ inputs.path }}/**"
  
  build:
    name: Build for web
    needs: detect
    if: needs.detect.outputs.changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build VSCode Web and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.path }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.artifact-name }}


  upload:
    name: Upload artifact
    needs: [detect, build]
    if: always() && needs.detect.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Pull from GitHub Container Registry
        run: |
          docker run --rm -v $(pwd):/out ghcr.io/${{ github.repository }}:${{ inputs.artifact-name }}
          mkdir -p _artifact
          unzip vscode-web.zip -d _artifact
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: _artifact
